language: java

sudo: false
cache:
  directories:
    - $HOME/.m2

env:
  - JDK=openjdk8
dist: trusty

branches:
  only:
    - master
    - GSOC_2017_kafka

before_install: 
  - "npm install -g grunt-cli bower@1.3.9"

before_script:
  - jdk_switcher use $JDK

script: "mvn verify javadoc:jar"
