language: java

sudo: required

# required for oraclejdk9
dist: trusty

# required for oraclejdk9
group: edge

jdk:
  - oraclejdk8
  - oraclejdk9

addons:
  sonarcloud:
    organization: "aerogear"
    token:
      secure: "G9JZpmpuYHSiPBnDH5SWRAomlpTi0+eBcTDKZT/ymGuR6oOR0OX+u7wXUGVb998MMt81VIjDz912sJJykFgzlx2THz8VHeUOu8QTbTBDbU/aNKJ+N7H52a5PDMxh2rPEs810JoyC7obgyrLSxyj/s2/xmJcnLTcjdBfP5hsxSBk="

matrix:
  allow_failures:
    - jdk: oraclejdk9

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
    - GSOC_2017_kafka

before_install: 
  - "npm install -g grunt-cli bower@1.3.9"

script: 
- mvn verify javadoc:jar
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

