version: '2.1'

services:
  unifiedpushserver:
    image: docker.io/aerogear/unifiedpush-wildfly:2.0.2
    volumes:
       - ./helper:/ups-helper:z
    entrypoint: "/ups-helper/exportKeycloakHost.sh"
    depends_on:
       unifiedpushDB:
         condition: service_healthy
    environment:
        POSTGRES_SERVICE_HOST: ${POSTGRES_SERVICE_HOST}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_SERVICE_PORT: ${POSTGRES_SERVICE_PORT}
        POSTGRES_DATABASE: ${POSTGRES_DATABASE}
        KEYCLOAK_SERVICE_HOST: ${KEYCLOAK_SERVICE_HOST}
        KEYCLOAK_SERVICE_PORT: ${KEYCLOAK_SERVICE_PORT}
    links:
      - unifiedpushDB:unifiedpush
      - keycloakServer:keycloak
    ports:
      - 9999:8080
  unifiedpushDB:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 20s
      retries: 10
  keycloakServer:
    image: docker.io/jboss/keycloak:3.4.3.Final
    command: "-b 0.0.0.0 -Dkeycloak.import=/ups-keycloak-config/ups-realm-sample.json"
    volumes:
      - ./keycloak-realm:/ups-keycloak-config:z
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
