version: '2.1'

services:
  unifiedpushserver:
    image: aerogear/unifiedpush-configurable-container:2.5.1-SNAPSHOT
    volumes:
       - ./helper:/ups-helper:z
    entrypoint: "/ups-helper/exportKeycloakHost.sh"
    depends_on:
       unifiedpushDB:
         condition: service_healthy
    environment:
        POSTGRES_SERVICE_HOST: ${POSTGRES_SERVICE_HOST}        
        KEYCLOAK_SERVICE_HOST: ${KEYCLOAK_SERVICE_HOST}
        KEYCLOAK_SERVICE_PORT: ${KEYCLOAK_SERVICE_PORT}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_SERVICE_PORT: ${POSTGRES_SERVICE_PORT}
        POSTGRES_DATABASE: ${POSTGRES_DATABASE}
        AMQ_MAX_RETRIES: ${AMQ_MAX_RETRIES}
        AMQ_BACKOFF_SECONDS: ${AMQ_BACKOFF_SECONDS}
    links:
      - unifiedpushDB:unifiedpush
      - artemis:artemis
      - keycloakServer:keycloak
    ports:
      - 9999:8080
  unifiedpushDB:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 20s
      retries: 10
    ports:
      - 5432:5432
  keycloakServer:
    image: docker.io/jboss/keycloak:11.0.0
    command: "-b 0.0.0.0 -Dkeycloak.import=/ups-keycloak-config/ups-realm-sample.json"
    volumes:
      - ./keycloak-realm:/ups-keycloak-config:z
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - 8080:8080
      - 8443:8443
  artemis:
    environment:
      ARTEMIS_USERNAME: ${ARTEMIS_USER}
      ARTEMIS_PASSWORD: ${ARTEMIS_PASSWORD}
    image: vromero/activemq-artemis
    volumes:
      - ./artemis-overrides:/var/lib/artemis/etc-override:z
    ports:
      - 8161:8161
      - 61616:61616
      - 61617:61617
 
