version: '2.1'

services:
  keycloakServer:
    image: docker.io/jboss/keycloak:3.4.3.Final
    command: "-b 0.0.0.0 -Dkeycloak.import=/ups-keycloak-config/ups-realm-sample.json"
    volumes:
      - ./keycloak-realm:/ups-keycloak-config:z
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
